version: '3'

services:
  db:
    image: 'mongo'
    container_name: MONGODB_ALLOCATION
    ports: 
      - '27017:27017'
    volumes:
      - .data/db:/data/db

  redis:
    image: 'bitnami/redis:latest'
    container_name: REDIS_ALLOCATION
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - '.data/redis:/data/redis'